# Generated by Django 4.2.7 on 2025-11-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_finder', '0001_initial'),
    ]

    operations = [
    ]
