# Generated by Django 4.2.7 on 2025-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_expression', models.TextField(help_text='Mathematical function expression')),
                ('method', models.CharField(choices=[('bisection', 'Bisection Method'), ('newton', 'Newton-Raphson Method'), ('secant', 'Secant Method')], max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Method-specific parameters')),
                ('root', models.FloatField(blank=True, null=True)),
                ('iterations', models.IntegerField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('converged', models.BooleanField(default=False)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('iteration_history', models.JSONField(default=list, help_text='Step-by-step iteration data')),
                ('tolerance', models.FloatField(default=1e-06)),
                ('max_iterations', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_expression', models.TextField()),
                ('tolerance', models.FloatField(default=1e-06)),
                ('max_iterations', models.IntegerField(default=100)),
                ('bisection_params', models.JSONField(blank=True, null=True)),
                ('newton_params', models.JSONField(blank=True, null=True)),
                ('secant_params', models.JSONField(blank=True, null=True)),
                ('results_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
